# Generated by Django 3.2.9 on 2021-11-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PabloAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
