# Generated by Django 3.2.9 on 2021-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PabloAplicacion', '0002_remove_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
