# Generated by Django 3.2.9 on 2021-11-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PabloAplicacion', '0004_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
