# Generated by Django 3.2.9 on 2021-11-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PabloAplicacion', '0005_remove_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
