# Generated by Django 3.2.9 on 2021-12-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PabloAplicacion', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('comentario', models.CharField(max_length=250)),
                ('last_login', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
